/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moneyapp;

/**
 *
 * @author YOGA 500
 */
public class Building extends javax.swing.JFrame {

    /**
     * Creates new form Building
     */
    public Building() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBuilding = new javax.swing.JTable();
        monthLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N

        jTableBuilding.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        jTableBuilding.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ร้านค้า1", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"ร้านค้า2", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"ร้านค้า3", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"ร้านค้า4", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"ร้านค้า5", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"101", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"102", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"103", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"104", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"105", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"201", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"202", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"203", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"204", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"205", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"206", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"207", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"208", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"209", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"210", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"211", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"212", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"301", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"302", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"303", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"304", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"305", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"306", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"307", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"308", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"309", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"310", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"311", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"312", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"401", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"402", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"403", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"404", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"405", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"405", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"407", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"408", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"409", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"410", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"411", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"412", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"501", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"502", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"503", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"504", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"505", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"506", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"507", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"508", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"509", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"510", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"511", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"512", null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ห้อง", "ค่าเช่าห้อง", "เลขมาตรน้ำครั้งนี้", "เลขมาตรน้ำครั้งก่อน", "จำนวนหน่วยน้ำ", "ค่าน้ำ", "เลขมาตรไฟครั้งนี้", "เลขมาตรไฟครั้งก่อน", "จำนวนหน่วยไฟ", "ค่าไฟ", "ค่าใช้จ่ายเพิ่ม", "ค่าใช้จ่ายลบ", "รวม", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableBuilding.setMinimumSize(new java.awt.Dimension(195, 1008));
        jTableBuilding.setRowHeight(30);
        jTableBuilding.setRowMargin(3);
        jScrollPane1.setViewportView(jTableBuilding);

        monthLabel.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        monthLabel.setText("เดือน");

        yearLabel.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        yearLabel.setText(" ปี");
        yearLabel.setToolTipText("");

        jComboBoxMonth.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนาคม", "กรกฎาคม", "สิงหายน", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม" }));
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });

        jComboBoxYear.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2558", "2559", "2560", " ", " " }));

        jButtonSave.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jButtonSave.setText("Save");

        jButton1.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        jButton1.setText("Print");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1054, 1054, 1054)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jButtonSave)
                                .addGap(84, 84, 84)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1843, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(monthLabel)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(657, 657, 657))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(monthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Building.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Building.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Building.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Building.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Building().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBuilding;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
